@extends('layouts.app')

@section('content')
    <h1 class="text-center my-5">HOME</h1>
    <div class="container"><hr>
        <p class="text-justify">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus semper commodo odio. Phasellus viverra orci in gravida consectetur. Mauris sagittis, odio eget suscipit laoreet, diam urna hendrerit neque, nec ullamcorper purus ligula at odio. Vivamus id ante in felis efficitur elementum id mattis mi. Ut non metus sed dolor accumsan luctus. Nulla eget imperdiet orci. Etiam ac metus venenatis, condimentum nisi fringilla, condimentum mi. Morbi maximus tortor arcu, nec posuere mi ultricies at.

        Integer sollicitudin dolor nec lacus euismod, quis faucibus nisl ultrices. Duis et ante eu massa sodales condimentum. Nulla bibendum, massa quis dictum venenatis, est libero tristique mauris, ac pulvinar ipsum dui eget libero. Cras a nibh blandit, feugiat velit sed, varius nunc. Cras hendrerit dignissim lectus, vitae porta tellus hendrerit quis. Fusce egestas dapibus turpis, et placerat enim tincidunt vitae. Suspendisse sodales ex a mauris elementum, eu ultricies eros pretium. Integer hendrerit mi in erat posuere porta. Nunc congue placerat molestie. Duis id mauris pharetra, tincidunt sapien porttitor, volutpat orci. Duis risus mauris, tempus mattis lectus et, aliquam finibus libero.<br><br>
            
        Duis porttitor, ipsum quis congue tempor, lectus elit euismod turpis, a suscipit mauris leo id dui. Integer a turpis a massa bibendum porttitor et non mi. Duis elementum erat in eros aliquet, non volutpat libero sollicitudin. Cras luctus euismod imperdiet. Aliquam mattis aliquam lacus et consectetur. Aliquam neque nulla, lacinia at felis vitae, egestas dictum ligula. Aliquam pellentesque ullamcorper sodales. Pellentesque ultrices eros sit amet nunc pellentesque, ac pretium tortor imperdiet.<br>
        Mauris iaculis est fermentum arcu varius semper non ac nibh. Praesent mattis turpis et sollicitudin dignissim. Donec in gravida magna. Maecenas venenatis lacus quis est feugiat tempus. Fusce placerat, odio sed fermentum iaculis, mi risus vestibulum tortor, in aliquet erat orci ut felis. Curabitur blandit iaculis efficitur. Phasellus quis iaculis augue, posuere consectetur dolor. Curabitur ultricies ante ut nulla ullamcorper porta. Integer iaculis ipsum purus. Praesent pulvinar erat pulvinar, egestas ante sit amet, volutpat velit. Maecenas lacinia faucibus diam eget dignissim. Vivamus nisl nisl, varius id diam in, fermentum consequat nunc. Aliquam sodales quam consequat, consectetur lacus quis, posuere diam. Integer quis eros vehicula elit suscipit volutpat. Praesent non volutpat mi, vitae mattis risus. Pellentesque sodales eget neque ut suscipit.</p>
    </div>
@endsection